const commonroute = (app, dynamicWrapper) => ({
  '/setting/dicManager': {
    component: dynamicWrapper(app, [], () => import('../routes/DicManager')),
  },
  '/setting/dicManager/list': {
    component: dynamicWrapper(app, [], () => import('../routes/DicManager/List')),
  },
  '/setting/dicManager/info': {
    component: dynamicWrapper(app, [], () => import('../routes/DicManager/Info')),
  },
  '/sqldebug': {
    component: dynamicWrapper(app, [], () => import('../routes/SqlDebug')),
  },
  '/sysFnc/oprLog': {
    component: dynamicWrapper(app, [], () => import('../routes/OprLog')),
  },
  '/sysFnc/oprLog/list': {
    component: dynamicWrapper(app, [], () => import('../routes/OprLog/List')),
  },
  '/sysFnc/oprLog/info': {
    component: dynamicWrapper(app, [], () => import('../routes/OprLog/Info')),
  },
  '/changePassword': {
    component: dynamicWrapper(app, [], () => import('../routes/User/ChangePassword')),
  },
  '/userInfo': {
    component: dynamicWrapper(app, [], () => import('../routes/User/UserInfo')),
  },
  '/user': {
    component: dynamicWrapper(app, [], () => import('../routes/User/List')),
  },
  '/usertype': {
    component: dynamicWrapper(app, [], () => import('../routes/BaseInfo/UserType')),
  },
  '/usertype/list': {
    component: dynamicWrapper(app, [], () => import('../routes/BaseInfo/UserType/List')),
  },
  '/usertype/info': {
    component: dynamicWrapper(app, [], () => import('../routes/BaseInfo/UserType/Info')),
  },
  '/T1wuyeyezhu': {
    component: dynamicWrapper(app, [], () => import('../routes/T1wuyeyezhu')),
  },
  '/T1wuyeyezhu/list': {
    component: dynamicWrapper(app, [], () => import('../routes/T1wuyeyezhu/List')),
  },
  '/T1wuyeyezhu/info': {
    component: dynamicWrapper(app, [], () => import('../routes/T1wuyeyezhu/Info')),
  },
  '/tuserInfo': {
    component: dynamicWrapper(app, [], () => import('../routes/TuserInfo')),
  },
  '/tuserInfo/list': {
    component: dynamicWrapper(app, [], () => import('../routes/TuserInfo/List')),
  },
  '/tuserInfo/info': {
    component: dynamicWrapper(app, ['tuserInfo'], () => import('../routes/TuserInfo/Info')),
  },
  '/TArroundshopandservice': {
    component: dynamicWrapper(app, [], () => import('../routes/TArroundshopandservice')),
  },
  '/TArroundshopandservice/list': {
    component: dynamicWrapper(app, [], () => import('../routes/TArroundshopandservice/List')),
  },
  '/TArroundshopandservice/info': {
    component: dynamicWrapper(app, [], () => import('../routes/TArroundshopandservice/Info')),
  },
  '/TProduct': {
    component: dynamicWrapper(app, [], () => import('../routes/TProduct')),
  },
  '/TProduct/list': {
    component: dynamicWrapper(app, [], () => import('../routes/TProduct/List')),
  },
  '/TProduct/info': {
    component: dynamicWrapper(app, [], () => import('../routes/TProduct/Info')),
  },
  '/TProducttype': {
    component: dynamicWrapper(app, [], () => import('../routes/TProducttype')),
  },
  '/TProducttype/list': {
    component: dynamicWrapper(app, [], () => import('../routes/TProducttype/List')),
  },
  '/TProducttype/info': {
    component: dynamicWrapper(app, [], () => import('../routes/TProducttype/Info')),
	},
	'/T1carfixedinfo':{  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedinfo')),  },
	'/T1carfixedinfo/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedinfo/List')),  },
	'/T1carfixedinfo/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedinfo/Info')),  },
	'/T1carfixedpayrecord':{  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedpayrecord')),  },
	'/T1carfixedpayrecord/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedpayrecord/List')),  },
	'/T1carfixedpayrecord/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedpayrecord/Info')),  },
	'/T1carfixedpricerule':{  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedpricerule')),  },
	'/T1carfixedpricerule/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedpricerule/List')),  },
	'/T1carfixedpricerule/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1carfixedpricerule/Info')),  },
	'/T1carstop':{  component: dynamicWrapper(app, [], () => import('../routes/T1carstop')),  },
	'/T1carstop/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1carstop/List')),  },
	'/T1carstop/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1carstop/Info')),  },
	'/T1cartmppricerule':{  component: dynamicWrapper(app, [], () => import('../routes/T1cartmppricerule')),  },
	'/T1cartmppricerule/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1cartmppricerule/List')),  },
	'/T1cartmppricerule/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1cartmppricerule/Info')),  },
	'/T1cartmprecord':{  component: dynamicWrapper(app, [], () => import('../routes/T1cartmprecord')),  },
	'/T1cartmprecord/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1cartmprecord/List')),  },
	'/T1cartmprecord/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1cartmprecord/Info')),  },
	'/T1wuyecoopreate':{  component: dynamicWrapper(app, [], () => import('../routes/T1wuyecoopreate')),  },
	'/T1wuyecoopreate/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyecoopreate/List')),  },
	'/T1wuyecoopreate/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyecoopreate/Info')),  },
	'/T1wuyecztj':{  component: dynamicWrapper(app, [], () => import('../routes/T1wuyecztj')),  },
	'/T1wuyecztj/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyecztj/List')),  },
	'/T1wuyecztj/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyecztj/Info')),  },
	'/T1wuyejiaofei':{  component: dynamicWrapper(app, [], () => import('../routes/T1wuyejiaofei')),  },
	'/T1wuyejiaofei/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyejiaofei/List')),  },
	'/T1wuyejiaofei/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyejiaofei/Info')),  },
	'/T1wuyeqftj':{  component: dynamicWrapper(app, [], () => import('../routes/T1wuyeqftj')),  },
	'/T1wuyeqftj/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyeqftj/List')),  },
	'/T1wuyeqftj/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyeqftj/Info')),  },
	'/T1wuyewuye':{  component: dynamicWrapper(app, [], () => import('../routes/T1wuyewuye')),  },
	'/T1wuyewuye/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyewuye/List')),  },
	'/T1wuyewuye/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyewuye/Info')),  },
	'/T1wuyexiaoqu':{  component: dynamicWrapper(app, [], () => import('../routes/T1wuyexiaoqu')),  },
	'/T1wuyexiaoqu/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyexiaoqu/List')),  },
	'/T1wuyexiaoqu/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyexiaoqu/Info')),  },
	'/T1wuyeyezhu':{  component: dynamicWrapper(app, [], () => import('../routes/T1wuyeyezhu')),  },
	'/T1wuyeyezhu/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyeyezhu/List')),  },
	'/T1wuyeyezhu/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1wuyeyezhu/Info')),  },
	'/TActivity':{  component: dynamicWrapper(app, [], () => import('../routes/TActivity')),  },
	'/TActivity/list': {  component: dynamicWrapper(app, [], () => import('../routes/TActivity/List')),  },
	'/TActivity/info': {  component: dynamicWrapper(app, [], () => import('../routes/TActivity/Info')),  },
	'/TActivitymsg':{  component: dynamicWrapper(app, [], () => import('../routes/TActivitymsg')),  },
	'/TActivitymsg/list': {  component: dynamicWrapper(app, [], () => import('../routes/TActivitymsg/List')),  },
	'/TActivitymsg/info': {  component: dynamicWrapper(app, [], () => import('../routes/TActivitymsg/Info')),  },
	'/TAgentcoopreate':{  component: dynamicWrapper(app, [], () => import('../routes/TAgentcoopreate')),  },
	'/TAgentcoopreate/list': {  component: dynamicWrapper(app, [], () => import('../routes/TAgentcoopreate/List')),  },
	'/TAgentcoopreate/info': {  component: dynamicWrapper(app, [], () => import('../routes/TAgentcoopreate/Info')),  },
	'/TArroundshopandservice':{  component: dynamicWrapper(app, [], () => import('../routes/TArroundshopandservice')),  },
	'/TArroundshopandservice/list': {  component: dynamicWrapper(app, [], () => import('../routes/TArroundshopandservice/List')),  },
	'/TArroundshopandservice/info': {  component: dynamicWrapper(app, [], () => import('../routes/TArroundshopandservice/Info')),  },
	'/TBanner':{  component: dynamicWrapper(app, [], () => import('../routes/TBanner')),  },
	'/TBanner/list': {  component: dynamicWrapper(app, [], () => import('../routes/TBanner/List')),  },
	'/TBanner/info': {  component: dynamicWrapper(app, [], () => import('../routes/TBanner/Info')),  },
	'/TBbs':{  component: dynamicWrapper(app, [], () => import('../routes/TBbs')),  },
	'/TBbs/list': {  component: dynamicWrapper(app, [], () => import('../routes/TBbs/List')),  },
	'/TBbs/info': {  component: dynamicWrapper(app, [], () => import('../routes/TBbs/Info')),  },
	'/TBbscomment':{  component: dynamicWrapper(app, [], () => import('../routes/TBbscomment')),  },
	'/TBbscomment/list': {  component: dynamicWrapper(app, [], () => import('../routes/TBbscomment/List')),  },
	'/TBbscomment/info': {  component: dynamicWrapper(app, [], () => import('../routes/TBbscomment/Info')),  },
	'/TBbsBak4':{  component: dynamicWrapper(app, [], () => import('../routes/TBbsBak4')),  },
	'/TBbsBak4/list': {  component: dynamicWrapper(app, [], () => import('../routes/TBbsBak4/List')),  },
	'/TBbsBak4/info': {  component: dynamicWrapper(app, [], () => import('../routes/TBbsBak4/Info')),  },
	'/TCommonskill':{  component: dynamicWrapper(app, [], () => import('../routes/TCommonskill')),  },
	'/TCommonskill/list': {  component: dynamicWrapper(app, [], () => import('../routes/TCommonskill/List')),  },
	'/TCommonskill/info': {  component: dynamicWrapper(app, [], () => import('../routes/TCommonskill/Info')),  },
	'/TGood':{  component: dynamicWrapper(app, [], () => import('../routes/TGood')),  },
	'/TGood/list': {  component: dynamicWrapper(app, [], () => import('../routes/TGood/List')),  },
	'/TGood/info': {  component: dynamicWrapper(app, [], () => import('../routes/TGood/Info')),  },
	'/TKeyvalue':{  component: dynamicWrapper(app, [], () => import('../routes/TKeyvalue')),  },
	'/TKeyvalue/list': {  component: dynamicWrapper(app, [], () => import('../routes/TKeyvalue/List')),  },
	'/TKeyvalue/info': {  component: dynamicWrapper(app, [], () => import('../routes/TKeyvalue/Info')),  },
	'/TMain':{  component: dynamicWrapper(app, [], () => import('../routes/TMain')),  },
	'/TMain/list': {  component: dynamicWrapper(app, [], () => import('../routes/TMain/List')),  },
	'/TMain/info': {  component: dynamicWrapper(app, [], () => import('../routes/TMain/Info')),  },
	'/TMsg':{  component: dynamicWrapper(app, [], () => import('../routes/TMsg')),  },
	'/TMsg/list': {  component: dynamicWrapper(app, [], () => import('../routes/TMsg/List')),  },
	'/TMsg/info': {  component: dynamicWrapper(app, [], () => import('../routes/TMsg/Info')),  },
	'/TMsglink':{  component: dynamicWrapper(app, [], () => import('../routes/TMsglink')),  },
	'/TMsglink/list': {  component: dynamicWrapper(app, [], () => import('../routes/TMsglink/List')),  },
	'/TMsglink/info': {  component: dynamicWrapper(app, [], () => import('../routes/TMsglink/Info')),  },
	'/TMycaredbbs':{  component: dynamicWrapper(app, [], () => import('../routes/TMycaredbbs')),  },
	'/TMycaredbbs/list': {  component: dynamicWrapper(app, [], () => import('../routes/TMycaredbbs/List')),  },
	'/TMycaredbbs/info': {  component: dynamicWrapper(app, [], () => import('../routes/TMycaredbbs/Info')),  },
	'/TPaydynamic':{  component: dynamicWrapper(app, [], () => import('../routes/TPaydynamic')),  },
	'/TPaydynamic/list': {  component: dynamicWrapper(app, [], () => import('../routes/TPaydynamic/List')),  },
	'/TPaydynamic/info': {  component: dynamicWrapper(app, [], () => import('../routes/TPaydynamic/Info')),  },
	'/TPicture':{  component: dynamicWrapper(app, [], () => import('../routes/TPicture')),  },
	'/TPicture/list': {  component: dynamicWrapper(app, [], () => import('../routes/TPicture/List')),  },
	'/TPicture/info': {  component: dynamicWrapper(app, [], () => import('../routes/TPicture/Info')),  },
	'/TPrivateopreate':{  component: dynamicWrapper(app, [], () => import('../routes/TPrivateopreate')),  },
	'/TPrivateopreate/list': {  component: dynamicWrapper(app, [], () => import('../routes/TPrivateopreate/List')),  },
	'/TPrivateopreate/info': {  component: dynamicWrapper(app, [], () => import('../routes/TPrivateopreate/Info')),  },
	'/TPrivatepersoncoopreate':{  component: dynamicWrapper(app, [], () => import('../routes/TPrivatepersoncoopreate')),  },
	'/TPrivatepersoncoopreate/list': {  component: dynamicWrapper(app, [], () => import('../routes/TPrivatepersoncoopreate/List')),  },
	'/TPrivatepersoncoopreate/info': {  component: dynamicWrapper(app, [], () => import('../routes/TPrivatepersoncoopreate/Info')),  },
	'/TProduct':{  component: dynamicWrapper(app, [], () => import('../routes/TProduct')),  },
	'/TProduct/list': {  component: dynamicWrapper(app, [], () => import('../routes/TProduct/List')),  },
	'/TProduct/info': {  component: dynamicWrapper(app, [], () => import('../routes/TProduct/Info')),  },
	'/TProducttrade':{  component: dynamicWrapper(app, [], () => import('../routes/TProducttrade')),  },
	'/TProducttrade/list': {  component: dynamicWrapper(app, [], () => import('../routes/TProducttrade/List')),  },
	'/TProducttrade/info': {  component: dynamicWrapper(app, [], () => import('../routes/TProducttrade/Info')),  },
	'/TProducttradeShop':{  component: dynamicWrapper(app, [], () => import('../routes/TProducttradeShop')),  },
	'/TProducttradeShop/list': {  component: dynamicWrapper(app, [], () => import('../routes/TProducttradeShop/List')),  },
	'/TProducttradeShop/info': {  component: dynamicWrapper(app, [], () => import('../routes/TProducttradeShop/Info')),  },
	'/TProducttype':{  component: dynamicWrapper(app, [], () => import('../routes/TProducttype')),  },
	'/TProducttype/list': {  component: dynamicWrapper(app, [], () => import('../routes/TProducttype/List')),  },
	'/TProducttype/info': {  component: dynamicWrapper(app, [], () => import('../routes/TProducttype/Info')),  },
	'/TProducttypeShop':{  component: dynamicWrapper(app, [], () => import('../routes/TProducttypeShop')),  },
	'/TProducttypeShop/list': {  component: dynamicWrapper(app, [], () => import('../routes/TProducttypeShop/List')),  },
	'/TProducttypeShop/info': {  component: dynamicWrapper(app, [], () => import('../routes/TProducttypeShop/Info')),  },
	'/TProductShop':{  component: dynamicWrapper(app, [], () => import('../routes/TProductShop')),  },
	'/TProductShop/list': {  component: dynamicWrapper(app, [], () => import('../routes/TProductShop/List')),  },
	'/TProductShop/info': {  component: dynamicWrapper(app, [], () => import('../routes/TProductShop/Info')),  },
	'/TRedmoneyapplyredraw':{  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneyapplyredraw')),  },
	'/TRedmoneyapplyredraw/list': {  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneyapplyredraw/List')),  },
	'/TRedmoneyapplyredraw/info': {  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneyapplyredraw/Info')),  },
	'/TRedmoneychangerecord':{  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneychangerecord')),  },
	'/TRedmoneychangerecord/list': {  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneychangerecord/List')),  },
	'/TRedmoneychangerecord/info': {  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneychangerecord/Info')),  },
	'/TRedmoneyrecord':{  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneyrecord')),  },
	'/TRedmoneyrecord/list': {  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneyrecord/List')),  },
	'/TRedmoneyrecord/info': {  component: dynamicWrapper(app, [], () => import('../routes/TRedmoneyrecord/Info')),  },
	'/TSharetotal':{  component: dynamicWrapper(app, [], () => import('../routes/TSharetotal')),  },
	'/TSharetotal/list': {  component: dynamicWrapper(app, [], () => import('../routes/TSharetotal/List')),  },
	'/TSharetotal/info': {  component: dynamicWrapper(app, [], () => import('../routes/TSharetotal/Info')),  },
	'/TTmp':{  component: dynamicWrapper(app, [], () => import('../routes/TTmp')),  },
	'/TTmp/list': {  component: dynamicWrapper(app, [], () => import('../routes/TTmp/List')),  },
	'/TTmp/info': {  component: dynamicWrapper(app, [], () => import('../routes/TTmp/Info')),  },
	'/TUserandformid':{  component: dynamicWrapper(app, [], () => import('../routes/TUserandformid')),  },
	'/TUserandformid/list': {  component: dynamicWrapper(app, [], () => import('../routes/TUserandformid/List')),  },
	'/TUserandformid/info': {  component: dynamicWrapper(app, [], () => import('../routes/TUserandformid/Info')),  },
	'/TUserwx':{  component: dynamicWrapper(app, [], () => import('../routes/TUserwx')),  },
	'/TUserwx/list': {  component: dynamicWrapper(app, [], () => import('../routes/TUserwx/List')),  },
	'/TUserwx/info': {  component: dynamicWrapper(app, [], () => import('../routes/TUserwx/Info')),  },
	'/TVer':{  component: dynamicWrapper(app, [], () => import('../routes/TVer')),  },
	'/TVer/list': {  component: dynamicWrapper(app, [], () => import('../routes/TVer/List')),  },
	'/TVer/info': {  component: dynamicWrapper(app, [], () => import('../routes/TVer/Info')),  },
	'/TVersioninfo':{  component: dynamicWrapper(app, [], () => import('../routes/TVersioninfo')),  },
	'/TVersioninfo/list': {  component: dynamicWrapper(app, [], () => import('../routes/TVersioninfo/List')),  },
	'/TVersioninfo/info': {  component: dynamicWrapper(app, [], () => import('../routes/TVersioninfo/Info')),  },
	'/TVirtual':{  component: dynamicWrapper(app, [], () => import('../routes/TVirtual')),  },
	'/TVirtual/list': {  component: dynamicWrapper(app, [], () => import('../routes/TVirtual/List')),  },
	'/TVirtual/info': {  component: dynamicWrapper(app, [], () => import('../routes/TVirtual/Info')),  },
	'/TVirtualtrade':{  component: dynamicWrapper(app, [], () => import('../routes/TVirtualtrade')),  },
	'/TVirtualtrade/list': {  component: dynamicWrapper(app, [], () => import('../routes/TVirtualtrade/List')),  },
	'/TVirtualtrade/info': {  component: dynamicWrapper(app, [], () => import('../routes/TVirtualtrade/Info')),  },
	'/TVirtualtype':{  component: dynamicWrapper(app, [], () => import('../routes/TVirtualtype')),  },
	'/TVirtualtype/list': {  component: dynamicWrapper(app, [], () => import('../routes/TVirtualtype/List')),  },
	'/TVirtualtype/info': {  component: dynamicWrapper(app, [], () => import('../routes/TVirtualtype/Info')),  },
	'/TWhocarewho':{  component: dynamicWrapper(app, [], () => import('../routes/TWhocarewho')),  },
	'/TWhocarewho/list': {  component: dynamicWrapper(app, [], () => import('../routes/TWhocarewho/List')),  },
	'/TWhocarewho/info': {  component: dynamicWrapper(app, [], () => import('../routes/TWhocarewho/Info')),  },
	'/TWuyechangerecord':{  component: dynamicWrapper(app, [], () => import('../routes/TWuyechangerecord')),  },
	'/TWuyechangerecord/list': {  component: dynamicWrapper(app, [], () => import('../routes/TWuyechangerecord/List')),  },
	'/TWuyechangerecord/info': {  component: dynamicWrapper(app, [], () => import('../routes/TWuyechangerecord/Info')),  },
	'/TWuyerchargerecord':{  component: dynamicWrapper(app, [], () => import('../routes/TWuyerchargerecord')),  },
	'/TWuyerchargerecord/list': {  component: dynamicWrapper(app, [], () => import('../routes/TWuyerchargerecord/List')),  },
	'/TWuyerchargerecord/info': {  component: dynamicWrapper(app, [], () => import('../routes/TWuyerchargerecord/Info')),  },
	'/TWuyeroominfo':{  component: dynamicWrapper(app, [], () => import('../routes/TWuyeroominfo')),  },
	'/TWuyeroominfo/list': {  component: dynamicWrapper(app, [], () => import('../routes/TWuyeroominfo/List')),  },
	'/TWuyeroominfo/info': {  component: dynamicWrapper(app, [], () => import('../routes/TWuyeroominfo/Info')),  },
	'/t_dic':{  component: dynamicWrapper(app, [], () => import('../routes/t_dic')),  },
	'/t_dic/list': {  component: dynamicWrapper(app, [], () => import('../routes/t_dic/List')),  },
	'/t_dic/info': {  component: dynamicWrapper(app, [], () => import('../routes/t_dic/Info')),  },
	'/T1kaimentongji':{  component: dynamicWrapper(app, [], () => import('../routes/T1kaimentongji')),  },
	'/T1kaimentongji/list': {  component: dynamicWrapper(app, [], () => import('../routes/T1kaimentongji/List')),  },
	'/T1kaimentongji/info': {  component: dynamicWrapper(app, [], () => import('../routes/T1kaimentongji/Info')),  },
	
	'/TClzBigtype':{  component: dynamicWrapper(app, [], () => import('../routes/TClzBigtype')),  },
	'/TClzBigtype/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzBigtype/List')),  },
	'/TClzBigtype/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzBigtype/Info')),  },
	'/TClzFood':{  component: dynamicWrapper(app, [], () => import('../routes/TClzFood')),  },
	'/TClzFood/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzFood/List')),  },
	'/TClzFood/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzFood/Info')),  },
	'/TClzSmalltype':{  component: dynamicWrapper(app, [], () => import('../routes/TClzSmalltype')),  },
	'/TClzSmalltype/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzSmalltype/List')),  },
	'/TClzSmalltype/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzSmalltype/Info')),  },
	'/TClzAssignfood':{  component: dynamicWrapper(app, [], () => import('../routes/TClzAssignfood')),  },
	'/TClzAssignfood/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzAssignfood/List')),  },
	'/TClzAssignfood/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzAssignfood/Info')),  },
	'/TClzDeliveryclerk':{  component: dynamicWrapper(app, [], () => import('../routes/TClzDeliveryclerk')),  },
	'/TClzDeliveryclerk/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzDeliveryclerk/List')),  },
	'/TClzDeliveryclerk/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzDeliveryclerk/Info')),  },
	'/TClzTodayOrder':{  component: dynamicWrapper(app, [], () => import('../routes/TClzTodayOrder')),  },
	'/TClzTodayOrder/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzTodayOrder/List')),  },
	'/TClzTodayOrder/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzTodayOrder/Info')),  },
	'/TClzHistoryOrder':{  component: dynamicWrapper(app, [], () => import('../routes/TClzHistoryOrder')),  },
	'/TClzHistoryOrder/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzHistoryOrder/List')),  },
	'/TClzHistoryOrder/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzHistoryOrder/Info')),  },
	'/TClzTomorrowOrder':{  component: dynamicWrapper(app, [], () => import('../routes/TClzTomorrowOrder')),  },
	'/TClzTomorrowOrder/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzTomorrowOrder/List')),  },
	'/TClzTomorrowOrder/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzTomorrowOrder/Info')),  },
	'/TClzTodayMatchOrder':{  component: dynamicWrapper(app, [], () => import('../routes/TClzTodayMatchOrder')),  },
	'/TClzTodayMatchOrder/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzTodayMatchOrder/List')),  },
	'/TClzTodayMatchOrder/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzTodayMatchOrder/Info')),  },
	'/TClzOrder':{  component: dynamicWrapper(app, [], () => import('../routes/TClzOrder')),  },
	'/TClzOrder/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzOrder/List')),  },
	'/TClzOrder/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzOrder/Info')),  },
	'/TClzOrderDatail':{  component: dynamicWrapper(app, [], () => import('../routes/TClzOrderDatail')),  },
	'/TClzOrderDatail/list': {  component: dynamicWrapper(app, [], () => import('../routes/TClzOrderDatail/List')),  },
	'/TClzOrderDatail/info': {  component: dynamicWrapper(app, [], () => import('../routes/TClzOrderDatail/Info')),  },
 
});

export default commonroute;
